# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBetamarket():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_betamarket(self):
    self.driver.get("https://betamarket.forte.kz/")
    self.driver.set_window_size(1050, 708)
    self.driver.find_element(By.LINK_TEXT, "Личный кабинет").click()
    self.driver.find_element(By.LINK_TEXT, "Выйти").click()
    self.driver.find_element(By.LINK_TEXT, "Войти").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mat-form-field-infix").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".mat-form-field-infix")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "mat-input-1").send_keys("+7 (777) 009 06 10")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-submit > .mat-button-wrapper").click()
    self.driver.find_element(By.ID, "mat-input-2").send_keys("Sberbank2030")
    self.driver.find_element(By.CSS_SELECTOR, ".mat-focus-indicator").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container > .categories").click()
    self.driver.find_element(By.LINK_TEXT, "Смартфоны и гаджеты").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container > .categories").click()
    self.driver.find_element(By.LINK_TEXT, "Смартфоны").click()
    self.driver.find_element(By.CSS_SELECTOR, ".medium-cat > .title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(4) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-star-inserted:nth-child(3) > span").click()
    self.driver.find_element(By.LINK_TEXT, "Мой профиль").click()
    self.driver.find_element(By.LINK_TEXT, "Изменить пароль").click()
    self.driver.find_element(By.LINK_TEXT, "Адреса и личные данные").click()
    self.driver.find_element(By.LINK_TEXT, "Маркет").click()
  
